import { assertEquals } from "jsr:@std/assert";
import { parseInput, solveFirst } from "./day08.ts";

const EXAMPLE_DATA: string = `............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............`;

Deno.test("Day 08, first part example works", () => {
    assertEquals(solveFirst(parseInput(EXAMPLE_DATA)), 14);
});
