import { assertEquals } from "jsr:@std/assert";
import { parseInput, solveFirst } from "./day06.ts";

const EXAMPLE_DATA: string = `....#.....
.........#
..........
..#.......
.......#..
..........
.#..^.....
........#.
#.........
......#...`;

Deno.test("Day 06, first part example works", () => {
    assertEquals(solveFirst(parseInput(EXAMPLE_DATA)), 41);
});
